In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [3]:
data_set = pd.read_csv("/Users/nikhilpradipmore/Downloads/Advertising.csv")

In [4]:
data_set.head()

   Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [5]:
data_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  200 non-null    int64
 1   TV          200 non-null    float64
 2   Radio       200 non-null    float64
 3   Newspaper   200 non-null    float64
 4   Sales       200 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 7.9 KB

In [6]:
data_set.isnull()

     Unnamed: 0     TV  Radio  Newspaper  Sales
0         False  False  False      False  False
1         False  False  False      False  False
2         False  False  False      False  False
3         False  False  False      False  False
4         False  False  False      False  False
..          ...    ...    ...        ...    ...
195       False  False  False      False  False
196       False  False  False      False  False
197       False  False  False      False  False
198       False  False  False      False  False
199       False  False  False      False  False

[200 rows x 5 columns]

In [7]:
data_set.isnull().sum()

Unnamed: 0    0
TV            0
Radio         0
Newspaper     0
Sales         0
dtype: int64

In [8]:
data_set.describe()

       Unnamed: 0          TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000  200.000000
mean   100.500000  147.042500   23.264000   30.554000   14.022500
std     57.879185   85.854236   14.846809   21.778621    5.217457
min      1.000000    0.700000    0.000000    0.300000    1.600000
25%     50.750000   74.375000    9.975000   12.750000   10.375000
50%    100.500000  149.750000   22.900000   25.750000   12.900000
75%    150.250000  218.825000   36.525000   45.100000   17.400000
max    200.000000  296.400000   49.600000  114.000000   27.000000

In [9]:
data_set.shape

(200, 5)

In [10]:
data_set.duplicated().sum()

np.int64(0)

In [11]:
data_set.columns

Index(['Unnamed: 0', 'TV', 'Radio', 'Newspaper', 'Sales'], dtype='object')

In [12]:
data_set = data_set.drop('Unnamed: 0', axis=1)

In [13]:
data_set

        TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [14]:
x = data_set.loc[:,data_set.columns != 'sales']

In [15]:
y = data_set.loc[:,data_set.columns != 'sales']

In [16]:
x

        TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [17]:
y

        TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

In [19]:
x_train

        TV  Radio  Newspaper  Sales
134   36.9   38.6       65.6   10.8
66    31.5   24.6        2.2    9.5
26   142.9   29.3       12.6   15.0
113  209.6   20.6       10.7   15.9
168  215.4   23.6       57.6   17.1
..     ...    ...        ...    ...
67   139.3   14.5       10.2   13.4
192   17.2    4.1       31.6    5.9
117   76.4    0.8       14.8    9.4
47   239.9   41.5       18.5   23.2
172   19.6   20.1       17.0    7.6

[160 rows x 4 columns]

In [20]:
x_test

        TV  Radio  Newspaper  Sales
18    69.2   20.5       18.3   11.3
170   50.0   11.6       18.4    8.4
107   90.4    0.3       23.2    8.7
98   289.7   42.3       51.2   25.4
177  170.2    7.8       35.2   11.7
182   56.2    5.7       29.7    8.7
5      8.7   48.9       75.0    7.2
146  240.1    7.3        8.7   13.2
12    23.8   35.1       65.9    9.2
152  197.6   23.3       14.2   16.6
61   261.3   42.7       54.7   24.2
125   87.2   11.8       25.9   10.6
180  156.6    2.6        8.3   10.5
154  187.8   21.1        9.5   15.6
80    76.4   26.7       22.3   11.8
7    120.2   19.6       11.6   13.2
33   265.6   20.0        0.3   17.4
130    0.7   39.6        8.7    1.6
37    74.7   49.4       45.7   14.7
74   213.4   24.6       13.1   17.0
183  287.6   43.0       71.8   26.2
145  140.3    1.9        9.0   10.3
45   175.1   22.5       31.5   14.9
159  131.7   18.4       34.6   12.9
60    53.5    2.0       21.4    8.1
123  123.1   34.6       12.4   15.2
179  165.6   10.0       17.6   12.6
185  205.0   45.1       19.6   22.6
122  224.0    2.4       15.6   11.6
44    25.1   25.7       43.3    8.5
16    67.8   36.6      114.0   12.5
55   198.9   49.4       60.0   23.7
150  280.7   13.9       37.0   16.1
111  241.7   38.0       23.2   21.8
22    13.2   15.9       49.6    5.6
189   18.7   12.1       23.4    6.7
129   59.6   12.0       43.1    9.7
4    180.8   10.8       58.4   12.9
83    68.4   44.5       35.6   13.6
106   25.0   11.0       29.7    7.2

In [21]:
y_train

        TV  Radio  Newspaper  Sales
134   36.9   38.6       65.6   10.8
66    31.5   24.6        2.2    9.5
26   142.9   29.3       12.6   15.0
113  209.6   20.6       10.7   15.9
168  215.4   23.6       57.6   17.1
..     ...    ...        ...    ...
67   139.3   14.5       10.2   13.4
192   17.2    4.1       31.6    5.9
117   76.4    0.8       14.8    9.4
47   239.9   41.5       18.5   23.2
172   19.6   20.1       17.0    7.6

[160 rows x 4 columns]

In [22]:
y_test

        TV  Radio  Newspaper  Sales
18    69.2   20.5       18.3   11.3
170   50.0   11.6       18.4    8.4
107   90.4    0.3       23.2    8.7
98   289.7   42.3       51.2   25.4
177  170.2    7.8       35.2   11.7
182   56.2    5.7       29.7    8.7
5      8.7   48.9       75.0    7.2
146  240.1    7.3        8.7   13.2
12    23.8   35.1       65.9    9.2
152  197.6   23.3       14.2   16.6
61   261.3   42.7       54.7   24.2
125   87.2   11.8       25.9   10.6
180  156.6    2.6        8.3   10.5
154  187.8   21.1        9.5   15.6
80    76.4   26.7       22.3   11.8
7    120.2   19.6       11.6   13.2
33   265.6   20.0        0.3   17.4
130    0.7   39.6        8.7    1.6
37    74.7   49.4       45.7   14.7
74   213.4   24.6       13.1   17.0
183  287.6   43.0       71.8   26.2
145  140.3    1.9        9.0   10.3
45   175.1   22.5       31.5   14.9
159  131.7   18.4       34.6   12.9
60    53.5    2.0       21.4    8.1
123  123.1   34.6       12.4   15.2
179  165.6   10.0       17.6   12.6
185  205.0   45.1       19.6   22.6
122  224.0    2.4       15.6   11.6
44    25.1   25.7       43.3    8.5
16    67.8   36.6      114.0   12.5
55   198.9   49.4       60.0   23.7
150  280.7   13.9       37.0   16.1
111  241.7   38.0       23.2   21.8
22    13.2   15.9       49.6    5.6
189   18.7   12.1       23.4    6.7
129   59.6   12.0       43.1    9.7
4    180.8   10.8       58.4   12.9
83    68.4   44.5       35.6   13.6
106   25.0   11.0       29.7    7.2

In [23]:
from sklearn.linear_model import LinearRegression

In [24]:
model = LinearRegression()

In [25]:
model.fit(x_train,y_train)

LinearRegression()

In [26]:
y_pred = model.predict(x_test)

In [27]:
y_pred

array([[ 69.2,  20.5,  18.3,  11.3],
       [ 50. ,  11.6,  18.4,   8.4],
       [ 90.4,   0.3,  23.2,   8.7],
       [289.7,  42.3,  51.2,  25.4],
       [170.2,   7.8,  35.2,  11.7],
       [ 56.2,   5.7,  29.7,   8.7],
       [  8.7,  48.9,  75. ,   7.2],
       [240.1,   7.3,   8.7,  13.2],
       [ 23.8,  35.1,  65.9,   9.2],
       [197.6,  23.3,  14.2,  16.6],
       [261.3,  42.7,  54.7,  24.2],
       [ 87.2,  11.8,  25.9,  10.6],
       [156.6,   2.6,   8.3,  10.5],
       [187.8,  21.1,   9.5,  15.6],
       [ 76.4,  26.7,  22.3,  11.8],
       [120.2,  19.6,  11.6,  13.2],
       [265.6,  20. ,   0.3,  17.4],
       [  0.7,  39.6,   8.7,   1.6],
       [ 74.7,  49.4,  45.7,  14.7],
       [213.4,  24.6,  13.1,  17. ],
       [287.6,  43. ,  71.8,  26.2],
       [140.3,   1.9,   9. ,  10.3],
       [175.1,  22.5,  31.5,  14.9],
       [131.7,  18.4,  34.6,  12.9],
       [ 53.5,   2. ,  21.4,   8.1],
       [123.1,  34.6,  12.4,  15.2],
       [165.6,  10. ,  17.6,  12.6],
       [205. ,  45.1,  19.6,  22.6],
       [224. ,   2.4,  15.6,  11.6],
       [ 25.1,  25.7,  43.3,   8.5],
       [ 67.8,  36.6, 114. ,  12.5],
       [198.9,  49.4,  60. ,  23.7],
       [280.7,  13.9,  37. ,  16.1],
       [241.7,  38. ,  23.2,  21.8],
       [ 13.2,  15.9,  49.6,   5.6],
       [ 18.7,  12.1,  23.4,   6.7],
       [ 59.6,  12. ,  43.1,   9.7],
       [180.8,  10.8,  58.4,  12.9],
       [ 68.4,  44.5,  35.6,  13.6],
       [ 25. ,  11. ,  29.7,   7.2]])

In [28]:
import pickle as pkl

In [29]:
filname = 'advertisingmodel.pkl'

In [30]:
pkl.dump(model,open(filname,'wb'))